### ISSUE TITLE
Distance always blurred

### ISSUE THREAD

**Issue by ghost** [Parallellines0451/GTAIV.EFLC.FusionShaders#19]
All distant objects are always blurred regardless of settings. Any help?

![GTAIV 2023-10-06 14-28-50](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/43250660/148989c5-d512-4c01-9512-3c313d7e3e6a)
![GTAIV 2023-10-06 14-29-22](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/43250660/92ec1369-427e-4710-89ab-c5ccf1e6a022)
![GTAIV 2023-10-06 14-29-26](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/43250660/5038fa42-90ab-4121-815d-ee27bc0d7dd7)

**Comment by Parallellines0451** [comment]
Normal behavior. What you're seeing is the filter used to smooth out stippled transparency. I'm looking into making the filter work like in GTA V, where it uses a mask to only blur out stippled objects instead of the whole screen; if that goes well that'll become the "Definition ON" setting in the next shaders/FF update.

http://www.adriancourreges.com/blog/2015/11/02/gta-v-graphics-study/#dithering-smoothing
