### ISSUE TITLE
[Feature Request] Screenspace godrays?

### ISSUE THREAD

**Issue by juicermv** [Parallellines0451/GTAIV.EFLC.FusionShaders#29]
I'm not sure how they are implemented, so I'm doing a bit of guessing here but would it be possible to implement something similar to RDR's screenspace godrays? It's a purely post process effect and the game already provides a similar effect (via a different method) for some local lights as you're probably aware. Here's an Nvidia article https://developer.nvidia.com/gpugems/gpugems3/part-ii-light-and-shadows/chapter-13-volumetric-light-scattering-post-process

**Comment by RecklessGlue540** [comment]
I think Max Payne 3, RDR1 and GTAV use ray marching... No idea if screenspace godrays even exist...

**Comment by juicermv** [comment]
The godrays in RDR1 are screenspace, this is very clear lol since they don't respect the sorting order of geometry and don't persist in world space. Literally boot up the game and see for yourself. Either way I have linked an Nvidia article that shows how this works.

**Comment by RecklessGlue540** [comment]
Either way, I agree that GTAIV's volumetric system is quite primitive. It only works for lights, but it also suffers from the same self shadowing issues the light models have, because of the lights sources being misplaced / not working correctly... 

Having a close (or an exact replica) to RDR1's / Max Payne 3's / V's  godrays would be a very nice improvement, considering it's very heavily used in Rockstar's art style. This would basically throw the need for ENBs out of the water.
And it's overall better to have these fully fledged sun godrays, instead of these bugged volumetric lights we currently have.

**Comment by juicermv** [comment]
Yup 100%

**Comment by juicermv** [comment]
Would love an update on this, whether this could be implemented at all. Again with RDR1 as reference.

**Comment by Parallellines0451** [comment]
> Would love an update on this, whether this could be implemented at all. Again with RDR1 as reference.

It definitely can, but we're not sure how yet. SSAO is in the works and will likely come first, then other effects might be investigated.

**Comment by RecklessGlue540** [comment]
<div style="width: 100%; height: 0px; position: relative; padding-bottom: 56.250%;"><iframe src="https://streamable.com/e/x2vbs2?quality=highest" frameborder="0" width="100%" height="100%" allowfullscreen style="width: 100%; height: 100%; position: absolute;"></iframe></div>

**Comment by juicermv** [comment]
Yup that's what I'm talking about!

**Comment by Parallellines0451** [comment]
Implemented through [ShadowResFix](https://github.com/RaphaelK12/ShadowResFix) and will be available in FusionFix soon.
