### ISSUE TITLE
New Shaders to Cast Shadows From Alpha Textures

### ISSUE THREAD

**Issue by BisonSales** [Parallellines0451/GTAIV.EFLC.FusionShaders#41]
Good day, talented professionals.

I wasn't sure if there was a possibility to add or change shaders to allow shadows to be cast from omni and spotlights when dynamic shadows are enabled? I know V uses a technique to allow night shadows from alpha textures for vegetation.

I believe I was working with AssaultKifle which he made some progress but wasn't sure if it was a dead end or just tabled the progress for the time being. He had a test with a chain link fence texture.

![image](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/155874969/fe9970ca-9013-4f00-bf91-d3949ca6f3a9)

Anyway, keep up the amazing work!!

**Comment by Parallellines0451** [comment]
Normally, for cascaded shadows, the game uses the cascadeGen shader to render most generic objects that have no transparency into the shadowmap; it doesn't have any texture resources because they're not useful in this case.
For objects that do have transparency, it uses the "WarpDepth" technique from each respective shader, which loads textures and does alpha testing, which is how fences are able to cast shadows from the sun.

ShadowZ is what's used to render objects into the tiles of the night shadow atlas and it's the only shader in the game that does that. It doesn't have a texture resource much like cascadeGen. The console developers used shadow casting lights very sparingly and never put objects with transparency near them; understandably they never felt the need to add support for that. The fence looks opaque when forced to cast a shadow because shadowZ can't load textures and can't do alpha testing. 

Adding transparency support would be quite a tremendous reverse engineering effort. That, and considering every other problem related to PC-only lights, means that solving this issue is out of scope.

PC shadow casting lampposts and headlights were not a properly implemented feature nor intended by the original developers, as you can see by all their problems and limitations, such as:
- bifurcated shadows: an artifact of the 360 degree projection that's normally not visible outside of lampposts and headlights due to clever light placement
- pop-in: since they were never meant to be viewed from long distances, fading was never implemented
- flickering: there's a limit on how many shadowmaps can fit in the atlas and having every lamppost and every headlight cast shadows means the game is always going over that limit and swapping lights around in the atlas
- inconsistency: some objects cast shadows from some lights and others don't, so you may end up in situations where you see shadows floating
- no transparency: as mentioned previously
- performance: they are [one of the main reasons why the game runs so poorly](https://gtaforums.com/topic/934545-fusionfix/page/47/#comment-1072249106) as most of these PC lights have a huge maximum range and no occlusion culling, so they render countless objects that can't even be seen by the player under any circumstances, including ones that are underground; just one single headlight can add upwards of 3000 draw calls

The next version of FusionFix will come with non shadow casting lampposts and headlights by default. Shadow casting may be restored through the ini, but it's not recommended.

If you allow me to make a suggestion: since you work with assets, please avoid adding more shadow casting lights or forcing more objects to cast shadows from artificial lights. This potentially adds thousands of extra draw calls per light and any visual benefit is negated by the aforementioned immersion breaking bugs. Shadow casting lights were never meant to be used en masse outside interiors and the PC version has erroneously had that for over fifteen years.

![Screenshot 2024-07-05 013707](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/133058741/a1abd46f-1bbf-458e-8da3-5c69e4e10445)
![Screenshot 2024-07-05 015102](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/133058741/800ec7bc-6628-4156-9acc-763b0d420f85)
![Screenshot 2024-07-05 014623](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/133058741/8e30c47f-7fb5-4615-bf2a-173b999dcfc2)
![Screenshot 2024-07-05 005351](https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/assets/133058741/8912115b-b814-4250-a28f-c865a075c447)
